name: Tag-release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Test on php ${{ matrix.php}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        php: [7.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set ENV for github-release
        run: |
          echo ::set-env name=RELEASE_TAG::$(echo ${GITHUB_REF:10})
          echo ::set-env name=RELEASE_NAME::"$GITHUB_WORKFLOW"

      - uses: meeDamian/github-release@2.0
        with:
          gzip: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
#          files: kite-${{ env.RELEASE_TAG }}.phar
